name: ztdl-cpu
channels:
- defaults
dependencies:
- python
- bz2file
- cython
- pip
- numpy
- jupyter
- matplotlib
- setuptools
- scikit-learn
- scipy
- pandas
- pillow
- seaborn
- pytest
- twisted
- pip:
  - tensorflow
